root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./bin/server ./cmd/server"
  bin = "./bin/server"
  delay = 1000
  exclude_dir = ["tmp", "bin"]
  include_ext = ["go"]
  kill_delay = "0s"
  rerun = false
  send_interrupt = false

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
